---
# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.

- name: Assert that "rivebot_install is sameas true" (boolean not string etc)
  assert:
    that: rivebot_install is sameas true
    fail_msg: "PLEASE SET 'rivebot_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "rivebot_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: rivebot_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'rivebot_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install RiveBot if 'rivebot_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: rivebot_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'rivebot' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: rivebot
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: RiveBot
        - option: description
          value: '"RiveBot is a deterministic RiveScript intent router for pre-LLM pattern matching"'
        - option: rivebot_install
          value: "{{ rivebot_install }}"
        - option: rivebot_enabled
          value: "{{ rivebot_enabled }}"
        - option: rivebot_port
          value: "{{ rivebot_port }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
