---
bagisto_headless_install: False
bagisto_headless_enabled: False
bagisto_headless_repo: "https://github.com/bagisto/nextjs-commerce.git"
bagisto_headless_version: "master"
bagisto_headless_dir: "/library/nextjs-commerce"
bagisto_headless_port: 3000
bagisto_api_package: "bagisto/bagisto-api:dev-master"
