---
- name: Assert that "ai_gateway_install is sameas true" (boolean not string etc)
  assert:
    that: ai_gateway_install is sameas true
    fail_msg: "PLEASE SET 'ai_gateway_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "ai_gateway_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: ai_gateway_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'ai_gateway_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install AI Gateway if 'ai_gateway_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: ai_gateway_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'ai_gateway' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: ai-gateway
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: AI Gateway
        - option: description
          value: '"AI Gateway is an OpenAI-compatible conversational AI orchestrator for IIAB"'
        - option: ai_gateway_install
          value: "{{ ai_gateway_install }}"
        - option: ai_gateway_enabled
          value: "{{ ai_gateway_enabled }}"
        - option: ai_gateway_port
          value: "{{ ai_gateway_port }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
