---
- name: Assert that "wuzapi_install is sameas true" (boolean not string etc)
  assert:
    that: wuzapi_install is sameas true
    fail_msg: "PLEASE SET 'wuzapi_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "wuzapi_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: wuzapi_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'wuzapi_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install WuzAPI if 'wuzapi_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: wuzapi_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'wuzapi' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: wuzapi
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: WuzAPI
        - option: description
          value: '"WuzAPI is a WhatsApp Web bridge using the whatsmeow Go library"'
        - option: wuzapi_install
          value: "{{ wuzapi_install }}"
        - option: wuzapi_enabled
          value: "{{ wuzapi_enabled }}"
        - option: wuzapi_port
          value: "{{ wuzapi_port }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
