---
- name: Assert that "bagisto_install is sameas true"
  assert:
    that: bagisto_install is sameas true
    fail_msg: "PLEASE SET 'bagisto_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "bagisto_enabled | type_debug == 'bool'"
  assert:
    that: bagisto_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'bagisto_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- block:
    - name: Install Bagisto if 'bagisto_installed' not defined
      include_tasks: install.yml
      when: bagisto_installed is undefined

    - name: Enable/Disable/Restart NGINX
      include_tasks: nginx.yml

    - name: Add 'bagisto' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: bagisto
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: Bagisto
        - option: description
          value: '"Bagisto Laravel E-Commerce Application"'
        - option: bagisto_install
          value: "{{ bagisto_install }}"
        - option: bagisto_enabled
          value: "{{ bagisto_enabled }}"
        - option: bagisto_abs_path
          value: "{{ bagisto_abs_path }}"

    - name: "BAGISTO-HEADLESS - run 'bagisto-headless' role"
      include_role:
        name: bagisto-headless
      when: bagisto_headless_install | default(False)

  rescue:
    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
