---
- name: Assert that "litellm_install is sameas true" (boolean not string etc)
  assert:
    that: litellm_install is sameas true
    fail_msg: "PLEASE SET 'litellm_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "litellm_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: litellm_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'litellm_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install LiteLLM if 'litellm_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: litellm_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'litellm' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: litellm
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: LiteLLM
        - option: description
          value: '"LiteLLM is an OpenAI-compatible proxy server for multiple LLM backends"'
        - option: litellm_install
          value: "{{ litellm_install }}"
        - option: litellm_enabled
          value: "{{ litellm_enabled }}"
        - option: litellm_port
          value: "{{ litellm_port }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
