---
- name: Enable & Restart 'organized' systemd service
  systemd:
    name: organized
    daemon_reload: yes
    enabled: yes
    state: restarted
  become: yes
  when: organized_enabled

- name: Disable & Stop 'organized' systemd service
  systemd:
    name: organized
    enabled: no
    state: stopped
  become: yes
  when: not organized_enabled

- name: Enable & Restart 'organized-celery' systemd service
  systemd:
    name: organized-celery
    daemon_reload: yes
    enabled: yes
    state: restarted
  become: yes
  when: organized_enabled

- name: Disable & Stop 'organized-celery' systemd service
  systemd:
    name: organized-celery
    enabled: no
    state: stopped
  become: yes
  when: not organized_enabled

- name: Install Nginx config, if enabled
  template:
    src: organized.conf.j2
    dest: /etc/nginx/conf.d/organized.conf
  become: yes
  when: organized_enabled
  notify: reload nginx

- name: Remove Nginx config, if disabled
  file:
    path: /etc/nginx/conf.d/organized.conf
    state: absent
  become: yes
  when: not organized_enabled
  notify: reload nginx
