---
- name: Assert that "openclaw_install is sameas true" (boolean not string etc)
  assert:
    that: openclaw_install is sameas true
    fail_msg: "PLEASE SET 'openclaw_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "openclaw_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: openclaw_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'openclaw_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install OpenClaw if 'openclaw_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: openclaw_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'openclaw' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: openclaw
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: OpenClaw
        - option: description
          value: '"OpenClaw is a conversational AI gateway for WhatsApp integration"'
        - option: openclaw_install
          value: "{{ openclaw_install }}"
        - option: openclaw_enabled
          value: "{{ openclaw_enabled }}"
        - option: openclaw_port
          value: "{{ openclaw_port }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
