---
# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.

- name: Assert that "siyuan_install is sameas true" (boolean not string etc)
  assert:
    that: siyuan_install is sameas true
    fail_msg: "PLEASE SET 'siyuan_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "siyuan_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: siyuan_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'siyuan_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes


- block:

    - name: Install SiYuan if 'siyuan_installed' not defined, e.g. in {{ iiab_state_file }}
      include_tasks: install.yml
      when: siyuan_installed is undefined

    - include_tasks: enable-or-disable.yml

    - name: Add 'siyuan' variable values to {{ iiab_ini_file }}
      ini_file:
        path: "{{ iiab_ini_file }}"
        section: siyuan
        option: "{{ item.option }}"
        value: "{{ item.value | string }}"
      with_items:
        - option: name
          value: SiYuan
        - option: description
          value: '"SiYuan is a note-taking and knowledge authoring server for IIAB"'
        - option: siyuan_install
          value: "{{ siyuan_install }}"
        - option: siyuan_enabled
          value: "{{ siyuan_enabled }}"
        - option: siyuan_port
          value: "{{ siyuan_port }}"
        - option: siyuan_version
          value: "{{ siyuan_version }}"

  rescue:

    - name: 'SEE ERROR ABOVE (skip_role_on_error: {{ skip_role_on_error }})'
      fail:
        msg: ""
      when: not skip_role_on_error
