---
- name: restart wuzapi
  systemd:
    name: wuzapi
    state: restarted
    daemon_reload: yes
  become: yes
  when: not is_proot

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: yes
  when: not is_proot
