---
dependencies: []

galaxy_info:
  role_name: visual
  description: "Bagisto Visual Theme Editor Extension for IIAB"
  author: "Internet-in-a-Box project"
  license: "GPLv3"
  min_ansible_version: "2.12"
